services:
  db:
    image: postgres:17.4-alpine
    container_name: postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: sampledb
      LANG: ja_JP.utf8
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  cache:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - 16379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass adminpass

  mq:
    image: rabbitmq:4.0.7-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminpass

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 18000:8000
    environment:
      - AWS_PROFILE=local
      - AWS_REGION=us-west-1
    volumes:
      - ./data:/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"

  dynamodb-init:
    image: amazon/aws-cli:latest
    container_name: dynamodb-init
    depends_on:
      - dynamodb
    environment:
      - AWS_PROFILE=local
      - AWS_REGION=us-west-1
    volumes:
      - ./init-dynamodb.d:/init-dynamodb.d
      - .aws:/root/.aws
    entrypoint: ["/bin/sh", "/init-dynamodb.d/init.sh"]
