version: '3'
services:
  db:
    image: postgres:15.5-alpine
    container_name: postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: sampledb
      LANG: ja_JP.utf8
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  kvs:
    image: amazon/dynamodb-local
    ports:
      - 18000:8000
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1

  cache:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - 16379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass adminpass

  mq:
    image: rabbitmq:3.13.0-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminpass
