name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
         cargo build --bin app-pq --features use_pq --verbose \
         cargo build --bin app-dynamo --features use_dynamo --verbose
    - name: Run tests
      run: |
        cargo test --features use_pq --verbose \
        cargo test --features use_dynamo --verbose
